CREATE TABLE Clickitorticket.users(
    user__id NUMBER GENERATED BY DEFAULT AS IDENTITY,
    username VARCHAR2(200),
    password_ VARCHAR2(200),
    email VARCHAR2(200),
    
    PRIMARY KEY(user__id)
);
-------------------------------------------------------------------------------------------------------------------------
CREATE TABLE Clickitorticket.button_types(
    button_type_id NUMBER GENERATED BY DEFAULT AS IDENTITY,
    button_type VARCHAR2(200),
    
    PRIMARY KEY(button_type_id)
);
-------------------------------------------------------------------------------------------------------------------------
CREATE TABLE Clickitorticket.buttons(
    button_id NUMBER GENERATED BY DEFAULT AS IDENTITY,
    button_image_src VARCHAR2(200),
    button_sound_src VARCHAR2(200),
    button_name VARCHAR2(50),
    button_type_id number,
	
    PRIMARY KEY(button_id),
	
	FOREIGN KEY (button_type_id)
        REFERENCES button_types (button_type_id)
        ON DELETE CASCADE
);
-------------------------------------------------------------------------------------------------------------------------
CREATE TABLE Clickitorticket.clicked(
    clicked_id NUMBER GENERATED BY DEFAULT AS IDENTITY,
    clicked_total NUMBER,
    click_date DATE NOT NULL,
    button_id NUMBER,
	user__id NUMBER,
	
    PRIMARY KEY(clicked_id),
	
	FOREIGN KEY (button_id)
        REFERENCES buttons (button_id),
		
	FOREIGN KEY (user__id)
        REFERENCES users (user__id)
        ON DELETE CASCADE
);
-------------------------------------------------------------------------------------------------------------------------
CREATE TABLE Clickitorticket.ratings(
    rating_id NUMBER GENERATED BY DEFAULT AS IDENTITY,
    rating_value NUMBER,
    rating_comment VARCHAR2(200),
    rating_date DATE NOT NULL,
	button_id NUMBER,
    
    PRIMARY KEY(rating_id),
	
	 FOREIGN KEY (button_id)
        REFERENCES buttons (button_id)
        ON DELETE CASCADE
);
---------------------------------------------------------------------------------------------------------------------------
CREATE TABLE Clickitorticket.users_ratings(
    user_rating NUMBER GENERATED BY DEFAULT AS IDENTITY,
    user__id NUMBER,
    rating_id NUMBER,

    PRIMARY KEY(user_rating),
	
	FOREIGN KEY (user__id)
        REFERENCES users (user__id)
        ON DELETE CASCADE,
		
		FOREIGN KEY (rating_id)
        REFERENCES ratings (rating_id)
        ON DELETE CASCADE,
				
				);
--------------------------------------------------------------------------------------------------------------------------------				
CREATE TABLE Clickitorticket.short_jokes(
    short_joke_id NUMBER GENERATED BY DEFAULT AS IDENTITY,
    short_joke_question VARCHAR2(200),
    short_joke_answer VARCHAR2(200),
    button_id NUMBER,

    PRIMARY KEY(short_joke_id),
	
	FOREIGN KEY (button_id)
        REFERENCES buttons (button_id)
        ON DELETE CASCADE
);
-----------------------------------------------------------------------------------------------------------------------------
CREATE TABLE Clickitorticket.yo_momma_jokes(
    yo_momma_joke_id NUMBER GENERATED BY DEFAULT AS IDENTITY,
    yo_momma_joke_question VARCHAR2(200),
    yo_momma_joke_answer VARCHAR2(200),
    button_id NUMBER,

    PRIMARY KEY(yo_momma_joke_id),
	
	FOREIGN KEY (button_id)
        REFERENCES buttons (button_id)
        ON DELETE CASCADE
);
-------------------------------------------------------------------------------------------------------------------------
CREATE TABLE Clickitorticket.bad_jokes(
    bad_joke_id NUMBER GENERATED BY DEFAULT AS IDENTITY,
    bad_joke_question VARCHAR2(200),
    bad_joke_answer VARCHAR2(200),
    button_id NUMBER,

    PRIMARY KEY(bad_joke_id),
	
	FOREIGN KEY (button_id)
        REFERENCES buttons (button_id)
        ON DELETE CASCADE
);
-----------------------------------------------------------------------------------------------------------------------------

CREATE TABLE Clickitorticket.phrases(
    phrase_id NUMBER GENERATED BY DEFAULT AS IDENTITY,
    phrase VARCHAR2(200),
    button_id NUMBER,

    PRIMARY KEY(phrase_id),
	
	FOREIGN KEY (button_id)
        REFERENCES buttons (button_id)
        ON DELETE CASCADE
);

-------------------------------------------------------------------------------------------------------------------------------------